# Generated by Django 5.0.6 on 2024-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField(max_length=10)),
                ("ext", models.CharField(max_length=5)),
                ("description", models.TextField()),
            ],
        ),
    ]
