# Generated by Django 5.0.6 on 2024-06-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="subject",
            field=models.TextField(null=True),
        ),
    ]
