# Generated by Django 5.0.6 on 2024-06-15 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_contact_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1000000000),
                    django.core.validators.MaxValueValidator(9999999999),
                ]
            ),
        ),
    ]
